### ISSUE TITLE
Infografía - Desarrollo de Software

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/infografia-IsaHuerta23#2]
Infografía 1 - Desarrollo de Software

[Infografía 1 - Desarrollo de Software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-IsaHuerta23/files/7123510/Infografia.1.-.Desarrollo.de.Software.pdf)

**Comment by ArturoAngonJose** [comment]
calificacion: 20/20 puntos

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
